# Generated by Django 6.0.7 on 2026-08-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_post_categoy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoy',
            new_name='category',
        ),
    ]
