# Generated by Django 6.0.7 on 2026-08-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_categoy_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='budget',
            field=models.CharField(default='Medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='destination',
            field=models.CharField(default='Medium', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.CharField(default='Medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='travel_style',
            field=models.CharField(default='Medium', max_length=100),
            preserve_default=False,
        ),
    ]
